import type {
  Sample,
  Scientist,
  Tests,
} from "./interfaces"; // Adjust path as needed

export const mockScientists: Scientist[] = [
  { id: 1, name: "Dr. Alice Nguyen", department: "Food Safety" },
  { id: 2, name: "Dr. Marcus Lee", department: "Cosmetic Chemistry" },
  { id: 3, name: "Dr. Priya Patel", department: "Microbiology" },
];

export const mockSamples: Sample[] = [
  {
    id: 1,
    name: "Strawberry Yogurt",
    owner: mockScientists[0],
    outOfSpec: false,
    testStart: new Date("2025-05-01"),
    totalSamples: 5,
    typeOfTest: { typeOfTest: "ph", lengthOfTest: "12 weeks" },
    sampleType: "food",
    testStatus: "in-progress",
    testDuration: "12-week",
    dueDate: new Date("2025-07-24"),
  },
  {
    id: 2,
    name: "Herbal Shampoo",
    owner: mockScientists[1],
    outOfSpec: true,
    testStart: new Date("2025-05-10"),
    totalSamples: 3,
    typeOfTest: { typeOfTest: "stability", lengthOfTest: "8 weeks" },
    sampleType: "cosmetic",
    testStatus: "in-progress",
    testDuration: "8-week",
    dueDate: new Date("2025-07-05"),
  },
  {
    id: 3,
    name: "Chocolate Pudding",
    owner: mockScientists[2],
    outOfSpec: false,
    testStart: new Date("2025-06-01"),
    totalSamples: 6,
    typeOfTest: { typeOfTest: "microbial", lengthOfTest: "4 weeks" },
    sampleType: "food",
    testStatus: "pending",
    testDuration: "4-week",
    dueDate: new Date("2025-07-01"),
  },
  {
    id: 4,
    name: "Aloe Vera Gel",
    owner: mockScientists[1],
    outOfSpec: false,
    testStart: new Date("2025-05-05"),
    totalSamples: 4,
    typeOfTest: { typeOfTest: "viscosity", lengthOfTest: "2 weeks" },
    sampleType: "cosmetic",
    testStatus: "completed",
    testDuration: "2-week",
    dueDate: new Date("2025-05-19"),
  },
  {
    id: 5,
    name: "Vanilla Ice Cream",
    owner: mockScientists[0],
    outOfSpec: true,
    testStart: new Date("2025-06-10"),
    totalSamples: 5,
    typeOfTest: { typeOfTest: "sensory", lengthOfTest: "1 week" },
    sampleType: "food",
    testStatus: "in-progress",
    testDuration: "1-week",
    dueDate: new Date("2025-06-17"),
  },
  {
    id: 6,
    name: "Cucumber Cleanser",
    owner: mockScientists[1],
    outOfSpec: false,
    testStart: new Date("2025-05-15"),
    totalSamples: 6,
    typeOfTest: { typeOfTest: "microbial", lengthOfTest: "4 weeks" },
    sampleType: "cosmetic",
    testStatus: "completed",
    testDuration: "4-week",
    dueDate: new Date("2025-06-15"),
  },
  {
    id: 7,
    name: "Almond Milk",
    owner: mockScientists[2],
    outOfSpec: false,
    testStart: new Date("2025-04-20"),
    totalSamples: 4,
    typeOfTest: { typeOfTest: "ph", lengthOfTest: "8 weeks" },
    sampleType: "food",
    testStatus: "completed",
    testDuration: "8-week",
    dueDate: new Date("2025-06-15"),
  },
  {
    id: 8,
    name: "Rose Lotion",
    owner: mockScientists[1],
    outOfSpec: false,
    testStart: new Date("2025-05-22"),
    totalSamples: 3,
    typeOfTest: { typeOfTest: "wateractivity", lengthOfTest: "2 weeks" },
    sampleType: "cosmetic",
    testStatus: "completed",
    testDuration: "2-week",
    dueDate: new Date("2025-06-05"),
  },
  {
    id: 9,
    name: "Protein Shake",
    owner: mockScientists[0],
    outOfSpec: false,
    testStart: new Date("2025-06-12"),
    totalSamples: 5,
    typeOfTest: { typeOfTest: "microbial", lengthOfTest: "1 week" },
    sampleType: "food",
    testStatus: "in-progress",
    testDuration: "1-week",
    dueDate: new Date("2025-06-19"),
  },
  {
    id: 10,
    name: "Honey Facial Mask",
    owner: mockScientists[1],
    outOfSpec: true,
    testStart: new Date("2025-05-18"),
    totalSamples: 4,
    typeOfTest: { typeOfTest: "sensory", lengthOfTest: "12 weeks" },
    sampleType: "cosmetic",
    testStatus: "in-progress",
    testDuration: "12-week",
    dueDate: new Date("2025-08-10"),
  },
  {
    id: 11,
    name: "Greek Yogurt",
    owner: mockScientists[0],
    outOfSpec: false,
    testStart: new Date("2025-06-01"),
    totalSamples: 5,
    typeOfTest: { typeOfTest: "wateractivity", lengthOfTest: "4 weeks" },
    sampleType: "food",
    testStatus: "pending",
    testDuration: "4-week",
    dueDate: new Date("2025-06-29"),
  },
  {
    id: 12,
    name: "Charcoal Scrub",
    owner: mockScientists[1],
    outOfSpec: false,
    testStart: new Date("2025-05-25"),
    totalSamples: 3,
    typeOfTest: { typeOfTest: "ph", lengthOfTest: "8 weeks" },
    sampleType: "cosmetic",
    testStatus: "in-progress",
    testDuration: "8-week",
    dueDate: new Date("2025-07-20"),
  },
  {
    id: 13,
    name: "Fruit Juice Blend",
    owner: mockScientists[2],
    outOfSpec: false,
    testStart: new Date("2025-06-05"),
    totalSamples: 4,
    typeOfTest: { typeOfTest: "viscosity", lengthOfTest: "2 weeks" },
    sampleType: "food",
    testStatus: "in-progress",
    testDuration: "2-week",
    dueDate: new Date("2025-06-19"),
  },
  {
    id: 14,
    name: "Coconut Conditioner",
    owner: mockScientists[1],
    outOfSpec: false,
    testStart: new Date("2025-06-08"),
    totalSamples: 6,
    typeOfTest: { typeOfTest: "stability", lengthOfTest: "8 weeks" },
    sampleType: "cosmetic",
    testStatus: "in-progress",
    testDuration: "8-week",
    dueDate: new Date("2025-08-03"),
  },
  {
    id: 15,
    name: "Vanilla Protein Bar",
    owner: mockScientists[0],
    outOfSpec: true,
    testStart: new Date("2025-06-15"),
    totalSamples: 7,
    typeOfTest: { typeOfTest: "wateractivity", lengthOfTest: "12 weeks" },
    sampleType: "food",
    testStatus: "in-progress",
    testDuration: "12-week",
    dueDate: new Date("2025-09-07"),
  },
];
